mutation resetPassword ($reset_code: String!, $password: String!) {
  resetPassword (reset_code: $reset_code, password: $password) {
    _id
    name
    username
    bio
    phone
    email
    password
    photo
    reset_code
    last_login
    token
  }
}
